
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzhlavnopnlmoejtioec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6aGxhdm5vcG5sbW9lanRpb2VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjI4OTksImV4cCI6MjA2MDAzODg5OX0.7IGzY3DjuNCNHwktzVURaOcNOPl4NiTiWI4tiIxVl7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
